name: Build and Release App

on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install customtkinter Pillow pyinstaller winshell pywin32 winsdk

    - name: Build with PyInstaller
      run: |
        # Bundling all icons and the app into one EXE
        pyinstaller --noconsole --onefile `
        --icon="icon.ico" `
        --add-data "prev.png;." `
        --add-data "play.png;." `
        --add-data "next.png;." `
        --add-data "shuffle.png;." `
        --add-data "repeat.png;." `
        --add-data "icon.ico;." `
        --collect-submodules winsdk `
        --collect-all winsdk `
        --hidden-import winsdk.windows.media.control `
        --name "MediaControl" main.py

    - name: Upload Executable
      uses: actions/upload-artifact@v4
      with:
        name: MediaControl-1.0
        path: dist/MediaControl.exe
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: dist/MediaControl.exe
        name: Media Control ${{ github.ref_name }}
        body: |
          ### Changes in this version
          - Added Vertical Volume Control
          - New Semicircle Hover Trigger
          - Shuffle/Repeat Toggle Support
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
